In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

**<h3>Loading the dataset</h3>**

In [3]:
df = pd.read_csv("train.txt", sep=';', header=None, names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

**<h3>Data Cleaning</h3>**

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

converting the output variables into numbers

In [8]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i += 1
    
df['emotion'] = df['emotion'].map(emotion_numbers)

In [9]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

changing all the text into the lower case

In [10]:
df['text'] = df['text'].apply(lambda x : x.lower())

removing the punctuations

In [11]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [12]:
df['text'] = df['text'].apply(remove_punc)

removing the numbers

In [14]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new


df['text'] = df['text'].apply(remove_numbers)