In [3]:
import numpy as np
import pandas as pd

**Merging two dataframes**

In [4]:
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'employee_name':['John','Jane','Jack','Jill','Jerry'],
    'department' :['HR','IT','Finance','IT','HR']
})

salaries = pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[50000,60000,70000,80000,90000],
    'bonus':[5000,6000,7000,8000,9000]
})

In [5]:
employees

   employee_id employee_name department
0            1          John         HR
1            2          Jane         IT
2            3          Jack    Finance
3            4          Jill         IT
4            5         Jerry         HR

In [6]:
salaries

   employee_id  salary  bonus
0            1   50000   5000
1            2   60000   6000
2            3   70000   7000
3            6   80000   8000
4            7   90000   9000