In [1]:
import numpy as np
import pandas as pd

In [20]:
company = pd.read_csv('Fortune_500_Companies.csv')
company.head()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [21]:
company.columns

Index(['Rank', 'Title', 'Website', 'Employees', 'Sector', 'Industry',
       'Hqlocation', 'Hqaddr', 'Hqcity', 'Hqstate', 'Hqzip', 'Hqtel', 'Ceo',
       'Ceo-title', 'Address', 'Ticker', 'Fullname', 'Revenues', 'Revchange',
       'Profits', 'Prftchange', 'Assets', 'Totshequity'],
      dtype='str')

GroupBy in sector

In [22]:
sectors = company.groupby('Sector')
sectors

In [23]:
len(company)

500

In [25]:
len(sectors)

21

In [28]:
sectors.size()

Sector
Aerospace & Defense              12
Apparel                           5
Business Services                20
Chemicals                        14
Energy                           57
Engineering & Construction       13
Financials                       84
Food & Drug Stores                7
Food, Beverages & Tobacco        24
Health Care                      38
Hotels, Restaurants & Leisure    10
Household Products               12
Industrials                      19
Materials                        19
Media                            11
Motor Vehicles & Parts            9
Retailing                        47
Technology                       43
Telecommunications               10
Transportation                   17
Wholesalers                      29
dtype: int64

In [34]:
sectors.size().sort_values(ascending=False)

Sector
Financials                       84
Energy                           57
Retailing                        47
Technology                       43
Health Care                      38
Wholesalers                      29
Food, Beverages & Tobacco        24
Business Services                20
Materials                        19
Industrials                      19
Transportation                   17
Chemicals                        14
Engineering & Construction       13
Household Products               12
Aerospace & Defense              12
Media                            11
Telecommunications               10
Hotels, Restaurants & Leisure    10
Motor Vehicles & Parts            9
Food & Drug Stores                7
Apparel                           5
dtype: int64

company from each sectors that occur in the first position

In [35]:
sectors.first()

,Rank,Title,Website,Employees,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Sector,,,,,,,,,,,,,,,,,,,,,
Aerospace & Defense,24,Boeing,http://www.boeing.com,150540,Aerospace and Defense,"Chicago, IL",100 N. Riverside Plaza,Chicago,IL,60606,...,"Chairman, President & Chief Executive Officer","100 N. Riverside Plaza, Chicago, IL 60606",BA,The Boeing Company,94571,-1.6,4895.0,-5.4,89997,817.0
Apparel,88,Nike,http://www.nike.com,70700,Apparel,"Beaverton, OR",1 Bowerman Dr.,Beaverton,OR,97005,...,"Chairman, President & Chief Executive Officer","1 Bowerman Dr., Beaverton, OR 97005",NKE,"Nike, Inc.",32376,5.8,3760.0,14.9,21396,12258.0
Business Services,146,ManpowerGroup,http://www.manpowergroup.com,28000,Temporary Help,"Milwaukee, WI",100 Manpower Place,Milwaukee,WI,53212,...,Chairman & Chief Executive Officer,"100 Manpower Place, Milwaukee, WI 53212",MAN,ManpowerGroup Inc.,19654,1.7,443.7,5.8,7574,2362.0
Chemicals,62,Dow Chemical,http://www.dow.com,56000,Chemicals,"Midland, MI",2030 Dow Center,Midland,MI,48674,...,Chairman & Chief Executive Officer,"2030 Dow Center, Midland, MI 48674",DOW,The Dow Chemical Company,48158,-1.3,4318.0,-43.8,79511,25987.0
Energy,4,Exxon Mobil,http://www.exxonmobil.com,72700,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
Engineering & Construction,149,Fluor,http://www.fluor.com,61551,"Engineering, Construction","Irving, TX",6700 Las Colinas Blvd.,Irving,TX,75039,...,Chairman & Chief Executive Officer,"6700 Las Colinas Blvd., Irving, TX 75039",FLR,Fluor Corporation,19037,5.1,281.4,-31.8,9216,3125.0
Financials,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,68131,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
Food & Drug Stores,17,Walgreens Boots Alliance,http://www.walgreensbootsalliance.com,300000,Food and Drug Stores,"Deerfield, IL",108 Wilmot Rd.,Deerfield,IL,60015,...,"President, Chief Executive Officer & Director","108 Wilmot Rd., Deerfield, IL 60015",WBA,"Walgreens Boots Alliance, Inc",117351,13.4,4173.0,-1.1,72688,29880.0
"Food, Beverages & Tobacco",44,PepsiCo,http://www.pepsico.com,264000,Food Consumer Products,"Purchase, NY",700 Anderson Hill Rd.,Purchase,NY,10577,...,Chairman & Chief Executive Officer,"700 Anderson Hill Rd., Purchase, NY 10577",PEP,"PepsiCo, Inc.",62799,-0.4,6329.0,16.1,74129,11095.0
Health Care,6,UnitedHealth Group,http://www.unitedhealthgroup.com,230000,Health Care: Insurance and Managed Care,"Minnetonka, MN",9900 Bren Rd. E.,Minnetonka,MN,55343,...,Chief Executive Officer & Director,"9900 Bren Rd. E., Minnetonka, MN 55343",UNH,UnitedHealth Group Incorporated,184840,17.7,7017.0,20.7,122810,38274.0
"Hotels, Restaurants & Leisure",112,McDonald’s,http://www.aboutmcdonalds.com,375000,Food Services,"Oak Brook, IL",1 McDonald's Plaza,Oak Brook,IL,60523,...,"President, Chief Executive Officer & Director","1 McDonald's Plaza, Oak Brook, IL 60523",MCD,McDonald's Corporation,24622,-3.1,4686.5,3.5,31024,-2204.0
Household Products,36,Procter & Gamble,http://www.pg.com,105000,Household and Personal Products,"Cincinnati, OH",1 Procter & Gamble Plaza,Cincinnati,OH,45202,...,"Chairman, President & Chief Executive Officer","1 Procter & Gamble Plaza, Cincinnati, OH 45202",PG,The Procter & Gamble Company,71726,-8.9,10508.0,49.3,127136,57341.0
Industrials,13,General Electric,http://www.ge.com,295000,Industrial Machinery,"Boston, MA",41 Farnsworth St.,Boston,MA,2210,...,Chairman & Chief Executive Officer,"41 Farnsworth St., Boston, MA 02210",GE,General Electric Company,126661,-9.8,8831.0,297.8,365183,75828.0
Materials,133,International Paper,http://www.internationalpaper.com,55000,"Packaging, Containers","Memphis, TN",6400 Poplar Ave.,Memphis,TN,38197,...,Chairman & Chief Executive Officer,"6400 Poplar Ave., Memphis, TN 38197",IP,International Paper Company,21079,-5.8,904.0,-3.6,33345,4341.0
Media,52,Disney,http://www.disney.com,195000,Entertainment,"Burbank, CA",500 S. Buena Vista St.,Burbank,CA,91521,...,Chairman & Chief Executive Officer,"500 S. Buena Vista St., Burbank, CA 91521",DIS,The Walt Disney Company,55632,6.0,9391.0,12,92033,43265.0
Motor Vehicles & Parts,8,General Motors,http://www.gm.com,225000,Motor Vehicles and Parts,"Detroit, MI",300 Renaissance Center,Detroit,MI,48265,...,Chairman & Chief Executive Officer,"300 Renaissance Center, Detroit, MI 48265",GM,General Motors Company,166380,9.2,9427.0,-2.7,221690,43836.0
Retailing,1,Walmart,http://www.walmart.com,2300000,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,72716,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
Technology,3,Apple,http://www.apple.com,116000,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
Telecommunications,9,AT&T,http://www.att.com,268540,Telecommunications,"Dallas, TX",208 S. Akard St.,Dallas,TX,75202,...,"Chairman, President & Chief Executive Officer","208 S. Akard St., Dallas, TX 75202",T,AT&T Inc.,163786,11.6,12976.0,-2.8,403821,123135.0
Transportation,46,UPS,http://www.ups.com,335520,"Mail, Package, and Freight Delivery","Atlanta, GA",55 Glenlake Pkwy. N.E.,Atlanta,GA,30328,...,Chairman & Chief Executive Officer,"55 Glenlake Pkwy. N.E., Atlanta, GA 30328",UPS,"United Parcel Service, Inc.",60906,4.4,3431.0,-29.2,40377,405.0
Wholesalers,5,McKesson,http://www.mckesson.com,68000,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,94104,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0